export const getFlag = (teamName: string): string => {
  const flags: Record<string, string> = {
    'Mexico': '🇲🇽',
    'South Africa': '🇿🇦',
    'South Korea': '🇰🇷',
    'Czech Republic': '🇨🇿',
    'Canada': '🇨🇦',
    'Bosnia and Herzegovina': '🇧🇦',
    'Qatar': '🇶🇦',
    'Switzerland': '🇨🇭',
    'Brazil': '🇧🇷',
    'Morocco': '🇲🇦',
    'Haiti': '🇭🇹',
    'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'United States': '🇺🇸',
    'USA': '🇺🇸',
    'Paraguay': '🇵🇾',
    'Australia': '🇦🇺',
    'Turkey': '🇹🇷',
    'Türkiye': '🇹🇷',
    'Germany': '🇩🇪',
    'Curacao': '🇨🇼',
    'Ivory Coast': '🇨🇮',
    'Ecuador': '🇪🇨',
    'Netherlands': '🇳🇱',
    'Japan': '🇯🇵',
    'Sweden': '🇸🇪',
    'Tunisia': '🇹🇳',
    'Belgium': '🇧🇪',
    'Egypt': '🇪🇬',
    'Iran': '🇮🇷',
    'New Zealand': '🇳🇿',
    'Spain': '🇪🇸',
    'Cape Verde': '🇨🇻',
    'Saudi Arabia': '🇸🇦',
    'Uruguay': '🇺🇾',
    'France': '🇫🇷',
    'Senegal': '🇸🇳',
    'Iraq': '🇮🇶',
    'Norway': '🇳🇴',
    'Argentina': '🇦🇷',
    'Algeria': '🇩🇿',
    'Austria': '🇦🇹',
    'Jordan': '🇯🇴',
    'Portugal': '🇵🇹',
    'Congo DR': '🇨🇩',
    'Uzbekistan': '🇺🇿',
    'Colombia': '🇨🇴',
    'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'Croatia': '🇭🇷',
    'Ghana': '🇬🇭',
    'Panama': '🇵🇦',
    'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'Peru': '🇵🇪',
    'Denmark': '🇩🇰',
    'Mali': '🇲🇱',
    'Cameroon': '🇨🇲',
    'Costa Rica': '🇨🇷',
    'Israel': '🇮🇱',
    'Nigeria': '🇳🇬',
    'Chile': '🇨🇱',
    'Italy': '🇮🇹',
    'Serbia': '🇷🇸',
    'Honduras': '🇭🇳',
    'China': '🇨🇳',
    'Poland': '🇵🇱'
  };

  // For knockout stage placeholders
  if (teamName.includes('Winner') || teamName.includes('Loser') || teamName.includes('Runner-up')) {
    return '🏳️';
  }

  return flags[teamName] || '🏴';
};
